on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
      - supermajor
      - major
      - minor
      - patch

jobs:

  format:
    if: ${{github.event.pull_request.changed_files > 0}}
    uses: ./.github/workflows/format.yaml
    secrets: inherit

  check:
    if: ${{github.event.pull_request.changed_files > 0}}
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  check-changelog:
    name: Check Changelog Action
    runs-on: ubuntu-20.04
    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
